name: Greeting Workflow
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a greeting
        run: echo "The CI pipeline has successfully started!"
      
      - name: Install pytest
        run: python3 -m pip install pytest
      - uses: actions/checkout@v4
      - name: Run Python Tests
        run: python3 -m test_calc.py
